name: mc_crud_test
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  provider: ^6.0.5
  get_it: ^7.2.0
  go_router: ^6.5.5
  flutter_svg: ^1.1.6
  intl_phone_number_input: ^0.7.2
  uuid: ^3.0.7
  flutter_keyboard_visibility: ^5.4.0
  hive_flutter: ^1.1.0
  pull_to_refresh: ^2.0.0
  animated_snack_bar: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  hive_generator: ^2.0.0
  flutter_lints: ^1.0.0
  mockito: ^5.4.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/